[package]
name = "social_media_app_v2"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
axum-extra = { version = "0.9", features = ["typed-header"] }  
headers = "0.4" 

sqlx = { version = "0.7", features = [
    "runtime-tokio-rustls",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
    "macros",
] }

tokio = { version = "1", features = ["full"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

chrono = { version = "0.4", features = ["serde"] }

uuid = { version = "1", features = ["v4", "serde"] }

bcrypt = "0.15"
jsonwebtoken = "9"

dotenvy = "0.15"

deadpool-redis = { version = "0.14", features = ["serde"] }
redis = { version = "0.25", features = ["tokio-comp", "tokio-rustls-comp"] }

tracing = "0.1"
tracing-subscriber = "0.3"

reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3

[profile.dev]
opt-level = 0
debug = true